name: Nx Workspace CI

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ $NODE_VERSION ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: $NODE_VERSION

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npx nx lint

    - name: Test
      run: npx nx test

    - name: Build
      run: npx nx build
